// ui
export const TOPBAR = 'topbar';
export const FOOTER = 'footer';
export const LOGINPAGE = 'loginpage';
export const LICENCE_PURCHASED = 'LICENCE_PURCHASED';
// auth
export const LOGIN = 'LOGIN';
export const REGISTRATION = 'REGISTRATION';
export const FORGOT_PASS_REQUEST = 'FORGOT_PASS_REQUEST';
export const FORGOT_PASS_OTP = 'FORGOT_PASS_OTP';
export const FORGOT_PASS_RESET = 'FORGOT_PASS_RESET';
export const FORGOT_PASS_DATA = 'FORGOT_PASS_DATA';
export const USER_EMAIL_VERIFY_SEND = 'USER_EMAIL_VERIFY_SEND';
export const USER_EMAIL_VERIFY_PROCESS = 'USER_EMAIL_VERIFY_PROCESS';
export const USER_MOBILE_VERIFY_PROCESS = 'USER_MOBILE_VERIFY_PROCESS';
export const USER_MOBILE_VERIFY_SEND = 'USER_MOBILE_VERIFY_SEND';
// user
export const USER_PROFILE_DETAILS = 'USER_PROFILE_DETAILS';
export const USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD';
export const USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE';
export const UPDATE_PROFILE_IMAGE = 'UPDATE_PROFILE_IMAGE';
export const GET_ALL_USER_CARDS = 'GET_ALL_USER_CARDS';
export const CREATE_USER_CARDS = 'CREATE_USER_CARDS';
export const UPDATE_USER_CARDS = 'UPDATE_USER_CARDS';
export const DELETE_USER_CARDS = 'DELETE_USER_CARDS';
export const GET_ALL_USER_BILLING_INFO = 'GET_ALL_USER_BILLING_INFO';
export const GET_USER_LICENSE = 'GET_USER_LICENSE';
export const GET_USER_WALLET = 'GET_USER_WALLET';

// common
export const UPLOAD_FILE_DATA = 'UPLOAD_FILE_DATA';
export const SEND_NOTIFICATION = 'SEND_NOTIFICATION';
export const TRANSACTION_LIST = 'TRANSACTION_LIST';
export const CREATE_FIREBASE_TOKEN = 'CREATE_FIREBASE_TOKEN';
export const GET_ACTIVE_TOKEN = 'GET_ACTIVE_TOKEN';
// Task
export const CREATE_TASK = 'CREATE_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const GET_ALL_RELATED_TASK = 'GET_ALL_RELATED_TASK';
export const CREATE_TASK_BOARD = 'CREATE_TASK_BOARD';
export const GET_TASK_BOARD_LIST = 'GET_TASK_BOARD_LIST';
export const CREATE_TASK_CATEGORY = 'CREATE_TASK_CATEGORY';
export const UPDATE_TASK_CATEGORY = 'UPDATE_TASK_CATEGORY';
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const ADD_RELATED_TASK = 'ADD_RELATED_TASK';
export const GET_TASK_LIST_BY_BOARD = 'GET_TASK_LIST_BY_BOARD';
export const ADD_ATTACHMENT = 'ADD_ATTACHMENT';
export const GET_TASK_ATTACHMENT = 'GET_TASK_ATTACHMENT';
export const GET_SINGLE_TASK = 'GET_SINGLE_TASK';
export const GET_ALL_TASK_KANBAN = 'GET_ALL_TASK_KANBAN';
export const GET_TASK_LIST_BY_PROJRCT_ID = 'GET_TASK_LIST_BY_PROJRCT_ID';
export const GET_ALL_TASK_BOARD_LIST = 'GET_ALL_TASK_BOARD_LIST';
export const TASK_COMMENT = 'TASK_COMMENT';
export const TASK_FILTER = 'TASK_FILTER';
export const GET_LOCATION_LIST = 'GET_LOCATION_LIST';
export const CREATE_LOCATION = 'CREATE_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const GET_ALL_UNIT = 'GET_ALL_UNIT';
export const GET_ALL_UNIT_BY_PROJECT_ID = 'GET_ALL_UNIT_BY_PROJECT_ID';
export const CREATE_TASK_CHECKLIST = 'CREATE_TASK_CHECKLIST';
export const GET_TASK_CHECKLIST = 'GET_TASK_CHECKLIST';
export const DELETE_TASK_CHECKLIST = 'DELETE_TASK_CHECKLIST';
export const UPDATE_TASK_CHECKLIST = 'UPDATE_TASK_CHECKLIST';
export const COPY_TASK = 'COPY_TASK';
export const USE_TEMPLATE = 'USE_TEMPLATE';

// Issues
export const GET_ISSUE_LIST = 'GET_ISSUE_LIST';
export const GET_ISSUE_DATA = 'GET_ISSUE_DATA';

// Project
export const GET_ALL_PROJECT = 'GET_ALL_PROJECT';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const LEAVE_PROJECT = 'LEAVE_PROJECT';
export const ARCHIVE_PROJECT = 'ARCHIVE_PROJECT';
export const UPDATE_PROJECT_SETTING = 'UPDATE_PROJECT_SETTING';
export const GET_PROJECT_DETAILS = 'GET_PROJECT_DETAILS';
export const GET_ALL_TEMPLATE = 'GET_ALL_TEMPLATE';
export const CREATE_PLAN_COMMENT = 'CREATE_PLAN_COMMENT';
export const GET_ALL_SHEETS_COMMENT = 'GET_ALL_SHEETS_COMMENT';
export const GET_ALL_TEMPLATE_CHECKLIST = 'GET_ALL_TEMPLATE_CHECKLIST';
export const CREATE_TEMPLATE = 'CREATE_TEMPLATE';
export const CREATE_CHECKLIST = 'CREATE_CHECKLIST';
export const DELETE_TEMPLATE = 'DELETE_TEMPLATE';
export const DELETE_CHECKLIST = 'DELETE_CHECKLIST';
export const UPDATE_PROJECT_TEMPLATE = 'UPDATE_PROJECT_TEMPLATE';
export const ADD_PROJECT_PHOTOS = 'ADD_PROJECT_PHOTOS';
export const ADD_MULTIPLE_PROJECT_PHOTOS = 'ADD_MULTIPLE_PROJECT_PHOTOS';
export const DELETE_PROJECT_PHOTOS = 'DELETE_PROJECT_PHOTOS';
export const UPDATE_PROJECT_PHOTO = 'UPDATE_PROJECT_PHOTO';
export const GET_ALL_PHOTOS = 'GET_ALL_PHOTOS';
export const CREATE_TAGS = 'CREATE_TAGS';
export const DELETE_TAGS = 'DELETE_TAGS';
export const UPDATE_TAGS = 'UPDATE_TAGS';
export const GET_ALL_TAGS = 'GET_ALL_TAGS';
export const CREATE_DIRECTORY = 'CREATE_DIRECTORY';
export const UPDATE_DIRECTORY = 'UPDATE_DIRECTORY';
export const DELETE_DIRECTORY = 'DELETE_DIRECTORY';
export const UPDATE_FILE_DIRECTORY = 'UPDATE_FILE_DIRECTORY';
export const CHANGE_FILE_DIRECTORY = 'CHANGE_FILE_DIRECTORY';
export const DELETE_FILE_DIRECTORY = 'DELETE_FILE_DIRECTORY';
export const CREATE_FILE = 'CREATE_FILE';
export const DELETE_FILE = 'DELETE_FILE';
export const GET_COUNT = 'GET_COUNT';
export const GET_REPORT_PERMISSION_LIST = 'GET_REPORT_PERMISSION_LIST';
export const REPORT_PERMISSION_STATUS = 'REPORT_PERMISSION_STATUS';
//STORE ROOM
export const CREATE_STORE_ROOM = 'CREATE_STORE_ROOM';
export const GET_STORE_ROOM = 'GET_STORE_ROOM';
export const UPDATE_STORE_ROOM = 'UPDATE_STORE_ROOM';
export const DELETE_STORE_ROOM = 'DELETE_STORE_ROOM';
export const GET_STORE_ROOM_FULL_DETAILS = 'GET_STORE_ROOM_FULL_DETAILS';
export const GET_ORDER_DETAILS_BY_STORE_ROOM_ID =
	'GET_ORDER_DETAILS_BY_STORE_ROOM_ID';
export const CREATE_UNIT = 'CREATE_UNIT';
export const UPDATE_UNIT = 'UPDATE_UNIT';
export const DELETE_UNIT = 'DELETE_UNIT';
export const CREATE_STORE_ROOM_PO = 'CREATE_STORE_ROOM_PO';
export const UPDATE_STORE_ROOM_PO = 'UPDATE_STORE_ROOM_PO';
export const DELIVERD_STORE_ROOM_PO_ORDER = 'DELIVERD_STORE_ROOM_PO_ORDER';
export const GET_STORE_ROOM_LOG_ID_AND_DATE = 'GET_STORE_ROOM_LOG_ID_AND_DATE';
export const GET_STORE_ROOM_REQUEST_LIST = 'GET_STORE_ROOM_REQUEST_LIST';
export const GET_STORE_ROOM_ADJUSTMENT_REQUEST_LIST =
	'GET_STORE_ROOM_ADJUSTMENT_REQUEST_LIST';
export const ISSUE_MATERIAL_REQUEST = 'ISSUE_MATERIAL_REQUEST';
export const SIGN_STORE_ROOM_LOG = 'SIGN_STORE_ROOM_LOG';
export const ADJUSTMENT_STORE_ROOM = 'ADJUSTMENT_STORE_ROOM';
export const CREATE_MATERIAL_INFO = 'CREATE_MATERIAL_INFO';
export const UPDATE_MATERIAL_INFO = 'UPDATE_MATERIAL_INFO';
export const GET_MATERIAL_LOG_LIST = 'GET_MATERIAL_LOG_LIST';
export const DELETE_MATERIAL_LOG = 'DELETE_MATERIAL_LOG';
export const GET_SINGLE_PO_DETAILS = 'GET_SINGLE_PO_DETAILS';
export const GET_MATERIAL_LOG_BY_DATE = 'GET_MATERIAL_LOG_BY_DATE';
export const SIGN_MATERIAL_LOG_REPORT = 'SIGN_MATERIAL_LOG_REPORT';
export const CONSUMPTION_MATERIAL = 'CONSUMPTION_MATERIAL';
export const REQUEST_MATERIAL = 'REQUEST_MATERIAL';
export const ADJUSTMENT_MATERIAL = 'ADJUSTMENT_MATERIAL';

// REPORTS
export const GET_SURVEY_REPORT = 'GET_SURVEY_REPORT';
export const GET_SURVEY_REPORT_BY_SURVEY_ID = 'GET_SURVEY_REPORT_BY_SURVEY_ID';
export const GET_SURVEY_REPORT_LIST_BY_SURVEY_ID =
	'GET_SURVEY_REPORT_LIST_BY_SURVEY_ID';
export const DELETE_SURVEY_REPORT = 'DELETE_SURVEY_REPORT';
export const SIGN_SURVEY_REPORT = 'SIGN_SURVEY_REPORT';
export const CREATE_SURVEY_REPORT = 'CREATE_SURVEY_REPORT';
export const UPDATE_SURVEY_REPORT = 'UPDATE_SURVEY_REPORT';
export const GET_QUESTIONS_LIST_BY_REQUEST_ID =
	'GET_QUESTIONS_LIST_BY_REQUEST_ID';
export const UNLOCK_REPORT = 'UNLOCK_REPORT';
export const GET_SURVEY_REPORT_BY_ID = 'GET_SURVEY_REPORT_BY_ID';
export const GET_SURVEY_REQUEST_DETAILS_BY_ID =
	'GET_SURVEY_REQUEST_DETAILS_BY_ID';

//LABOUR AND EQUIPMENT LOG
export const GET_LABOUR_AND_EQUIPMENT_LOG_BY_PROJECT_ID =
	'GET_LABOUR_AND_EQUIPMENT_LOG_BY_PROJECT_ID';
export const GET_LABOUR_AND_EQUIPMENT_DETAILS =
	'GET_LABOUR_AND_EQUIPMENT_DETAILS';
export const CREATE_LABOUR_AND_EQUIPMENT_LOG =
	'CREATE_LABOUR_AND_EQUIPMENT_LOG';
export const UPDATE_LABOUR_AND_EQUIPMENT_LOG =
	'UPDATE_LABOUR_AND_EQUIPMENT_LOG';
export const DELETE_LABOUR_AND_EQUIPMENT_LOG =
	'DELETE_LABOUR_AND_EQUIPMENT_LOG';

//SHEET PLANS
export const DELETE_PLAN = 'DELETE_PLAN';
export const CREATE_PLAN = 'CREATE_PLAN';
export const UPDATE_SHEET_PLAN = 'UPDATE_SHEET_PLAN';
export const GET_RELATED_SHEET = 'GET_RELATED_SHEET';
export const ADD_RELATED_SHEET = 'ADD_RELATED_SHEET';
export const GET_RELATED_FILES = 'GET_RELATED_FILES';
export const ADD_SHEET_PHOTOS = 'ADD_SHEET_PHOTOS';
export const GET_ALL_SHEETS_PHOTOS = 'GET_ALL_SHEETS_PHOTOS';
export const DELETE_SHEET_RELATED_PHOTOS = 'DELETE_SHEET_RELATED_PHOTOS';
export const ADD_RELATED_FILES = 'ADD_RELATED_FILES';
export const ADD_PLAN_REVISION = 'ADD_PLAN_REVISION';
export const PLAN_REVISION_INDEX_UPDATE = 'PLAN_REVISION_INDEX_UPDATE';
export const DELETE_REVISION = 'DELETE_REVISION';
export const GET_SHEET_DETAILS_BY_ID = 'GET_SHEET_DETAILS_BY_ID';
export const SHARE_PLANS = 'SHARE_PLANS';
export const REVISION_RENAME = 'REVISION_RENAME';

//SHEET PLANS
export const UPDATE_PROJECT_TEMPLATE_CHECKLIST =
	'UPDATE_PROJECT_TEMPLATE_CHECKLIST';
export const MOVE_PLAN_DIRECTORY = 'MOVE_PLAN_DIRECTORY';
export const CREATE_MEETING = 'CREATE_MEETING';
export const DELETE_MEETING = 'DELETE_MEETING';
export const UPDATE_MEETING = 'UPDATE_MEETING';
export const CREATE_POINT = 'CREATE_POINT';
export const GET_ALL_MEETING_LIST = 'GET_ALL_MEETING_LIST';
export const GET_ALL_SUBPOINT_LIST = 'GET_ALL_SUBPOINT_LIST';
export const CREATE_SUB_POINT = 'CREATE_SUB_POINT';
export const DELETE_MEETING_SUB_POINT = 'DELETE_MEETING_SUB_POINT';
export const UPDATE_MEETING_SUB_POINT = 'UPDATE_MEETING_SUB_POINT';
export const INVITE_MEETING_USER = 'INVITE_MEETING_USER';
export const DELETE_MEETING_POINT = 'DELETE_MEETING_POINT';
export const UPDATE_MEETING_POINT = 'UPDATE_MEETING_POINT';
export const GET_ALL_MATERIAL_LIST = 'GET_ALL_MATERIAL_LIST';
export const GET_MATERIAL_DETAILS_BY_ID = 'GET_MATERIAL_DETAILS_BY_ID';
export const ADD_MATERIAL = 'ADD_MATERIAL';
export const UPDATE_MATERIAL = 'UPDATE_MATERIAL';
export const DELETE_MATERIAL = 'DELETE_MATERIAL';
export const GET_ALL_LABOUR_LIST = 'GET_ALL_LABOUR_LIST';
export const GET_LABOUR_LOG_BY_PROJECT_ID = 'GET_LABOUR_LOG_BY_PROJECT_ID';
export const CREATE_LABOUR = 'CREATE_LABOUR';
export const CREATE_LABOUR_LOG = 'CREATE_LABOUR_LOG';
export const UPDATE_LABOUR = 'UPDATE_LABOUR';
export const UPDATE_LABOUR_LOG = 'UPDATE_LABOUR_LOG';
export const DELETE_LABOUR = 'DELETE_LABOUR';
export const DELETE_LABOUR_LOG = 'DELETE_LABOUR_LOG';
export const GET_ALL_EQUIPMENT_LIST = 'GET_ALL_EQUIPMENT_LIST';
export const GET_ALL_EQUIPMENT_LOG_LIST_BY_ID_AND_DATE =
	'GET_ALL_EQUIPMENT_LOG_LIST_BY_ID_AND_DATE';
export const CREATE_EQUIPMENT_LOG = 'CREATE_EQUIPMENT_LOG';
export const UPDATE_EQUIPMENT_LOG = 'UPDATE_EQUIPMENT_LOG';
export const CREATE_EQUIPMENT = 'CREATE_EQUIPMENT';
export const DELETE_EQUIPMENT = 'DELETE_EQUIPMENT';
export const UPDATE_EQUIPMENT = 'UPDATE_EQUIPMENT';
export const GET_ALL_TIMESHEET_LIST = 'GET_ALL_TIMESHEET_LIST';
export const SIGN_LABOUR_AND_EQUIPMENT_LOG = 'SIGN_LABOUR_AND_EQUIPMENT_LOG';
export const CREATE_TIMESHEET = 'CREATE_TIMESHEET';
export const DELETE_TIMESHEET = 'DELETE_TIMESHEET';
export const UPDATE_TIMESHEET = 'UPDATE_TIMESHEET';
export const GET_ALL_INSPECTION_LIST = 'GET_ALL_INSPECTION_LIST';
export const CREATE_INSPECTION = 'CREATE_INSPECTION';
export const DELETE_INSPECTION = 'DELETE_INSPECTION';
export const UPDATE_INSPECTION = 'UPDATE_INSPECTION';

//people
export const GET_ALL_ROLE = 'GET_ALL_ROLE';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const INVITE_USER = 'INVITE_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const CREATE_USER_ROLE = 'CREATE_USER_ROLE';
export const GET_USER_ROLE_BY_ID = 'GET_USER_ROLE_BY_ID';
export const UPDATE_USER_ROLE_BY_ID = 'UPDATE_USER_ROLE_BY_ID';
export const DELETE_USER_ROLE_BY_ID = 'DELETE_USER_ROLE_BY_ID';
export const GET_ALL_ROLE_WISE_PEOPLE = 'GET_ALL_ROLE_WISE_PEOPLE';
export const GET_ALL_ACCESS_KEYS = 'GET_ALL_ACCESS_KEYS';
export const GET_ALL_ROLE_ACCESS_KEYS = 'GET_ALL_ROLE_ACCESS_KEYS';
// files
export const GET_ALL_FILE_DIRECTORIES = 'GET_ALL_FILE_DIRECTORIES';
export const GET_ALL_FILE_LIST_DIRECTORIES_WISE =
	'GET_ALL_FILE_LIST_DIRECTORIES_WISE';
export const UPDATE_FILE_NAME = 'UPDATE_FILE_NAME';
export const SHARE_FILES = 'SHARE_FILES';
// sheets
export const GET_ALL_SHEETS = 'GET_ALL_SHEETS';
export const GET_RECENT_SHEETS = 'GET_RECENT_SHEETS';

//License
export const GET_LICENSE_PLANS = 'GET_LICENSE_PLANS';
export const CREATE_BILLING_INFO = 'CREATE_BILLING_INFO';
export const EDIT_BILLING_INFO = 'EDIT_BILLING_INFO';

// Loading
export const LOADING_DATA = 'LOADING_DATA'
export const AUTH_LOADING = 'AUTH_LOADING';
export const FILE_UPLOAD_LOADING = 'FILE_UPLOAD_LOADING';

//Notification
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const GET_NOTIFICATION_COUNT = "GET_NOTIFICATION_COUNT";
export const GET_PROJECT_NOTIFICATION_COUNT = "GET_PROJECT_NOTIFICATION_COUNT";
export const GET_NOTIFICATION_BY_PROJECT = 'GET_NOTIFICATION_BY_PROJECT';
export const READ_NOTIFICATION = 'READ_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';

// Team
//people
export const GET_ALL_ROLE_TEAM = 'GET_ALL_ROLE_TEAM';
export const UPDATE_ROLE_TEAM = 'UPDATE_ROLE_TEAM';
export const INVITE_USER_TEAM = 'INVITE_USER_TEAM';
export const REMOVE_USER_TEAM = 'REMOVE_USER_TEAM';
export const CREATE_USER_ROLE_TEAM = 'CREATE_USER_ROLE_TEAM';
export const GET_USER_ROLE_BY_ID_TEAM = 'GET_USER_ROLE_BY_ID_TEAM';
export const UPDATE_USER_ROLE_BY_ID_TEAM = 'UPDATE_USER_ROLE_BY_ID_TEAM';
export const DELETE_USER_ROLE_BY_ID_TEAM = 'DELETE_USER_ROLE_BY_ID_TEAM';
export const GET_ALL_ROLE_WISE_PEOPLE_TEAM = 'GET_ALL_ROLE_WISE_PEOPLE_TEAM';
export const GET_ALL_ACCESS_KEYS_TEAM = 'GET_ALL_ACCESS_KEYS_TEAM';

// RFI 
export const GET_RFI_LIST = 'GET_RFI_LIST';


// Vendor
export const GET_VENDOR_LIST = "GET_VENDOR_LIST";

// TASK WALL
export const GET_WALL_LIST = "GET_WALL_LIST";

// Image Light Box
export const LIGHTBOX_VIEW_STATUS = 'LIGHTBOX_VIEW_STATUS';
export const LIGHTBOX_IMAGES = 'LIGHTBOX_IMAGES';
export const LIGHTBOX_DEFAULT_URL = 'LIGHTBOX_DEFAULT_URL';
